Amanda wasserman
gnarayan/ast596_2023_Spring pull request #57
Opened 2023-03-03 08:05 UTC by AmandaWasserman

2023-03-06 05:38 UTC, AmandaWasserman commented
Pretty sure I'm done with the midterm. Turning it in so I stop thinking about it. Might fix some things later in the week when I talk to people about it if I have time.

2023-03-18 02:23 UTC, Samantha-Thrush requested changes
Please change your pull request to only affect files within your folder.

2023-03-20 19:16 UTC, AmandaWasserman commented
I think I fixed it? Let me know if that worked

2023-03-21 01:54 UTC, Samantha-Thrush approved these changes

2023-03-21 01:54 UTC, merged